// <auto-generated />
using System;
using System.Text.Json;
using HealthPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527062954_AddAuditLogImmutabilityTriggers")]
    partial class AddAuditLogImmutabilityTriggers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthPlatform.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsWalkIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_walk_in");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("PreferredSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_slot_id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<DateTimeOffset>("SlotTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("slot_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_appointments_provider_id");

                    b.HasIndex("SlotId")
                        .IsUnique()
                        .HasDatabaseName("ix_appointments_slot_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.AppointmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_appointment_slots");

                    b.HasIndex("ProviderId", "StartTime")
                        .HasDatabaseName("ix_appointment_slots_provider_id_start_time");

                    b.ToTable("appointment_slots", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("current_hash");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_type");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_hash");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.ClinicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("processing_status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_clinical_documents");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_clinical_documents_patient_id");

                    b.ToTable("clinical_documents", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.DataConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field");

                    b.Property<Guid>("PatientViewId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_view_id");

                    b.Property<string>("ResolutionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("resolution_status");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SourceDocA")
                        .HasColumnType("uuid")
                        .HasColumnName("source_doc_a");

                    b.Property<Guid>("SourceDocB")
                        .HasColumnType("uuid")
                        .HasColumnName("source_doc_b");

                    b.Property<string>("ValueA")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value_a");

                    b.Property<string>("ValueB")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value_b");

                    b.HasKey("Id")
                        .HasName("pk_data_conflicts");

                    b.HasIndex("PatientViewId")
                        .HasDatabaseName("ix_data_conflicts_patient_view_id");

                    b.ToTable("data_conflicts", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.ExtractedData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_score");

                    b.Property<string>("DataCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("data_category");

                    b.Property<JsonDocument>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("pk_extracted_data");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_extracted_data_document_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_extracted_data_patient_id");

                    b.ToTable("extracted_data", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.InsuranceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("member_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_insurance_records");

                    b.ToTable("insurance_records", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            MemberId = "MBR-000001",
                            ProviderName = "BlueCross BlueShield",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            MemberId = "MBR-000002",
                            ProviderName = "BlueCross BlueShield",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            MemberId = "MBR-000003",
                            ProviderName = "BlueCross BlueShield",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            MemberId = "MBR-000004",
                            ProviderName = "BlueCross BlueShield",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            MemberId = "MBR-000005",
                            ProviderName = "BlueCross BlueShield",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            MemberId = "MBR-000006",
                            ProviderName = "Aetna Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            MemberId = "MBR-000007",
                            ProviderName = "Aetna Health",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            MemberId = "MBR-000008",
                            ProviderName = "Aetna Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            MemberId = "MBR-000009",
                            ProviderName = "Aetna Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000010"),
                            MemberId = "MBR-000010",
                            ProviderName = "Aetna Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000011"),
                            MemberId = "MBR-000011",
                            ProviderName = "United Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000012"),
                            MemberId = "MBR-000012",
                            ProviderName = "United Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000013"),
                            MemberId = "MBR-000013",
                            ProviderName = "United Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000014"),
                            MemberId = "MBR-000014",
                            ProviderName = "United Healthcare",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000015"),
                            MemberId = "MBR-000015",
                            ProviderName = "United Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000016"),
                            MemberId = "MBR-000016",
                            ProviderName = "Cigna Medical",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000017"),
                            MemberId = "MBR-000017",
                            ProviderName = "Cigna Medical",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000018"),
                            MemberId = "MBR-000018",
                            ProviderName = "Cigna Medical",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000019"),
                            MemberId = "MBR-000019",
                            ProviderName = "Cigna Medical",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000020"),
                            MemberId = "MBR-000020",
                            ProviderName = "Cigna Medical",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000021"),
                            MemberId = "MBR-000021",
                            ProviderName = "Humana Insurance",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000022"),
                            MemberId = "MBR-000022",
                            ProviderName = "Humana Insurance",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000023"),
                            MemberId = "MBR-000023",
                            ProviderName = "Humana Insurance",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000024"),
                            MemberId = "MBR-000024",
                            ProviderName = "Humana Insurance",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000025"),
                            MemberId = "MBR-000025",
                            ProviderName = "Humana Insurance",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000026"),
                            MemberId = "MBR-000026",
                            ProviderName = "Anthem BCBS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000027"),
                            MemberId = "MBR-000027",
                            ProviderName = "Anthem BCBS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000028"),
                            MemberId = "MBR-000028",
                            ProviderName = "Anthem BCBS",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000029"),
                            MemberId = "MBR-000029",
                            ProviderName = "Anthem BCBS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000030"),
                            MemberId = "MBR-000030",
                            ProviderName = "Anthem BCBS",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000031"),
                            MemberId = "MBR-000031",
                            ProviderName = "Molina Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000032"),
                            MemberId = "MBR-000032",
                            ProviderName = "Molina Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000033"),
                            MemberId = "MBR-000033",
                            ProviderName = "Molina Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000034"),
                            MemberId = "MBR-000034",
                            ProviderName = "Molina Healthcare",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000035"),
                            MemberId = "MBR-000035",
                            ProviderName = "Molina Healthcare",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000036"),
                            MemberId = "MBR-000036",
                            ProviderName = "Centene Corporation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000037"),
                            MemberId = "MBR-000037",
                            ProviderName = "Centene Corporation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000038"),
                            MemberId = "MBR-000038",
                            ProviderName = "Centene Corporation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000039"),
                            MemberId = "MBR-000039",
                            ProviderName = "Centene Corporation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000040"),
                            MemberId = "MBR-000040",
                            ProviderName = "Centene Corporation",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000041"),
                            MemberId = "MBR-000041",
                            ProviderName = "WellCare Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000042"),
                            MemberId = "MBR-000042",
                            ProviderName = "WellCare Health",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000043"),
                            MemberId = "MBR-000043",
                            ProviderName = "WellCare Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000044"),
                            MemberId = "MBR-000044",
                            ProviderName = "WellCare Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000045"),
                            MemberId = "MBR-000045",
                            ProviderName = "WellCare Health",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000046"),
                            MemberId = "MBR-000046",
                            ProviderName = "Kaiser Permanente",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000047"),
                            MemberId = "MBR-000047",
                            ProviderName = "Kaiser Permanente",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000048"),
                            MemberId = "MBR-000048",
                            ProviderName = "Kaiser Permanente",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000049"),
                            MemberId = "MBR-000049",
                            ProviderName = "Kaiser Permanente",
                            Status = "Inactive"
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000050"),
                            MemberId = "MBR-000050",
                            ProviderName = "Kaiser Permanente",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.IntakeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<JsonDocument>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("mode");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_intake_records");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_intake_records_appointment_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_intake_records_patient_id");

                    b.ToTable("intake_records", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.MedicalCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code_type");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("PatientViewId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_view_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("Id")
                        .HasName("pk_medical_codes");

                    b.HasIndex("PatientViewId")
                        .HasDatabaseName("ix_medical_codes_patient_view_id");

                    b.ToTable("medical_codes", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("channel");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_notifications_appointment_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_notifications_patient_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("InsuranceMemberId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("insurance_member_id");

                    b.Property<string>("InsuranceProviderName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("insurance_provider_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_patient_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_profiles_user_id");

                    b.ToTable("patient_profiles", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PatientView360", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConflictCount")
                        .HasColumnType("integer")
                        .HasColumnName("conflict_count");

                    b.Property<JsonDocument>("ConsolidatedDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("consolidated_data_json");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_patient_views360");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("ix_patient_views360_patient_id");

                    b.ToTable("patient_views360", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PreferredSlotPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<Guid>("PreferredSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("preferred_slot_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_preferred_slot_preferences");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_preferred_slot_preferences_appointment_id");

                    b.ToTable("preferred_slot_preferences", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ScheduleTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_template_id");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_providers");

                    b.ToTable("providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Dr. Sarah Mitchell",
                            Specialty = "Cardiology",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Dr. James Okafor",
                            Specialty = "General Practice",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Dr. Priya Sharma",
                            Specialty = "Neurology",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Dr. Marcus Chen",
                            Specialty = "Orthopedics",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Dr. Fatima Al-Rashid",
                            Specialty = "Pediatrics",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.PatientProfile", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_patient_profiles_patient_id");

                    b.HasOne("HealthPlatform.Domain.Entities.Provider", "Provider")
                        .WithMany("Appointments")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_providers_provider_id");

                    b.HasOne("HealthPlatform.Domain.Entities.AppointmentSlot", "Slot")
                        .WithOne("Appointment")
                        .HasForeignKey("HealthPlatform.Domain.Entities.Appointment", "SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_appointment_slots_slot_id");

                    b.Navigation("Patient");

                    b.Navigation("Provider");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.AppointmentSlot", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.Provider", "Provider")
                        .WithMany("AppointmentSlots")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointment_slots_providers_provider_id");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.ClinicalDocument", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.PatientProfile", "Patient")
                        .WithMany("ClinicalDocuments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_documents_patient_profiles_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.DataConflict", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.PatientView360", "PatientView")
                        .WithMany("DataConflicts")
                        .HasForeignKey("PatientViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_data_conflicts_patient_views360_patient_view_id");

                    b.Navigation("PatientView");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.ExtractedData", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.ClinicalDocument", "Document")
                        .WithMany("ExtractedData")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extracted_data_clinical_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.IntakeRecord", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.Appointment", "Appointment")
                        .WithOne("IntakeRecord")
                        .HasForeignKey("HealthPlatform.Domain.Entities.IntakeRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intake_records_appointments_appointment_id");

                    b.HasOne("HealthPlatform.Domain.Entities.PatientProfile", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intake_records_patient_profiles_patient_id");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.MedicalCode", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.PatientView360", "PatientView")
                        .WithMany("MedicalCodes")
                        .HasForeignKey("PatientViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medical_codes_patient_views360_patient_view_id");

                    b.Navigation("PatientView");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Notifications")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_appointments_appointment_id");

                    b.HasOne("HealthPlatform.Domain.Entities.PatientProfile", "Patient")
                        .WithMany("Notifications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_patient_profiles_patient_id");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PatientProfile", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("HealthPlatform.Domain.Entities.PatientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PatientView360", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.PatientProfile", "Patient")
                        .WithOne("PatientView360")
                        .HasForeignKey("HealthPlatform.Domain.Entities.PatientView360", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_views360_patient_profiles_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PreferredSlotPreference", b =>
                {
                    b.HasOne("HealthPlatform.Domain.Entities.Appointment", "Appointment")
                        .WithOne("PreferredSlotPreference")
                        .HasForeignKey("HealthPlatform.Domain.Entities.PreferredSlotPreference", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preferred_slot_preferences_appointments_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("IntakeRecord");

                    b.Navigation("Notifications");

                    b.Navigation("PreferredSlotPreference");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.AppointmentSlot", b =>
                {
                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.ClinicalDocument", b =>
                {
                    b.Navigation("ExtractedData");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PatientProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ClinicalDocuments");

                    b.Navigation("Notifications");

                    b.Navigation("PatientView360");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.PatientView360", b =>
                {
                    b.Navigation("DataConflicts");

                    b.Navigation("MedicalCodes");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.Provider", b =>
                {
                    b.Navigation("AppointmentSlots");

                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HealthPlatform.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PatientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
